[features]
seeds = true
skip-lint = false
[programs.localnet]
todo_list_anchor = "5LKhTzPmPJfiunQ6NAimso7sZhG3kiLw8jx9xzKUAh68"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/home/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
